# Generated by Django 3.2.9 on 2021-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layth',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
