# Generated by Django 3.2.9 on 2021-11-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_taha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layth',
        ),
        migrations.DeleteModel(
            name='Taha',
        ),
    ]
